services:
  app:
    build: .
    command: pnpm --filter client dev
    container_name: headquarters_app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/client/node_modules
      - /app/apps/server/node_modules
    ports:
      - "5173:5173"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/headquarters
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: headquarters_db
    ports:
      - "27018:27017"